<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>gw</AssemblyName>
    <RootNamespace></RootNamespace>
    <OutputType>Exe</OutputType>
    <StartupObject>Greaseweazle.Cli.Driver</StartupObject>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="**\*.vb" Exclude="bin\**\*;obj\**\*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Greaseweazle\Greaseweazle.vbproj" />
  </ItemGroup>
</Project>
