<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Greaseweazle</AssemblyName>
    <RootNamespace></RootNamespace>
    <OutputType>Library</OutputType>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <Version>1.23.0.3</Version>
    <AssemblyVersion>1.23.0.3</AssemblyVersion>
    <FileVersion>1.23.0.3</FileVersion>
    <InformationalVersion>1.23.3</InformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="**\*.vb" Exclude="bin\**\*;obj\**\*" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="data\*.xml" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.IO.Compression" />
  </ItemGroup>
</Project>
